create table if not exists tata_baber_hero_settings (
    id bigint generated by default as identity primary key,
    location_label text not null default 'LOCATION',
    wrapper_max_width integer not null default 1820,
    side_gap_desktop integer not null default 0,
    side_gap_tablet integer not null default 0,
    side_gap_mobile integer not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists tata_baber_hero_slides (
    id text primary key,
    sort_order integer not null default 1,
    active boolean not null default true,
    tab_title text not null,
    eyebrow text,
    image_url text not null,
    thumb_url text,
    address_html text,
    email text,
    phone text,
    updated_at timestamptz not null default now()
);

create index if not exists tata_baber_hero_slides_sort_order_idx on tata_baber_hero_slides (sort_order);

create table if not exists tata_baber_about_images (
    id text primary key,
    sort_order integer not null default 1,
    active boolean not null default true,
    image_url text not null,
    alt_text text,
    updated_at timestamptz not null default now()
);

create index if not exists tata_baber_about_images_sort_order_idx on tata_baber_about_images (sort_order);

insert into storage.buckets (id, name, public)
values ('tata-baber', 'tata-baber', true)
on conflict (id) do update set public = excluded.public;

insert into tata_baber_hero_settings (location_label, wrapper_max_width, side_gap_desktop, side_gap_tablet, side_gap_mobile)
select 'LOCATION', 1820, 0, 0, 0
where not exists (select 1 from tata_baber_hero_settings);

insert into tata_baber_hero_slides (id, sort_order, active, tab_title, eyebrow, image_url, thumb_url, address_html, email, phone)
select 'hero-slide-1', 1, true, 'BARBERING', 'MAKE YOUR STYLE MORE EXPRESSIVE', './images-tatabarber/banner01.jpg', './images-tatabarber/banner01.jpg', 'Husitská 27, Praha 3', '', '+420 773 338 678'
where not exists (select 1 from tata_baber_hero_slides where id = 'hero-slide-1');

insert into tata_baber_hero_slides (id, sort_order, active, tab_title, eyebrow, image_url, thumb_url, address_html, email, phone)
select 'hero-slide-2', 2, true, 'GROOMING & SHAVING', 'FROM FADES TO BUZZ CUTS', './images-tatabarber/banner01.jpg', './images-tatabarber/banner01.jpg', 'Husitská 27, Praha 3', '', '+420 773 338 678'
where not exists (select 1 from tata_baber_hero_slides where id = 'hero-slide-2');

insert into tata_baber_hero_slides (id, sort_order, active, tab_title, eyebrow, image_url, thumb_url, address_html, email, phone)
select 'hero-slide-3', 3, true, 'MANICURE & SPA', 'PREMIUM CARE FOR EVERY DETAIL', './images-tatabarber/banner02.jpg', './images-tatabarber/banner02.jpg', 'Husitská 27, Praha 3', '', '+420 773 338 678'
where not exists (select 1 from tata_baber_hero_slides where id = 'hero-slide-3');

insert into tata_baber_about_images (id, sort_order, active, image_url, alt_text)
select 'about-image-1', 1, true, 'wp-content/uploads/2023/04/about-3-1.jpg', 'Tata BarberShop haircut detail'
where not exists (select 1 from tata_baber_about_images where id = 'about-image-1');

insert into tata_baber_about_images (id, sort_order, active, image_url, alt_text)
select 'about-image-2', 2, true, 'wp-content/uploads/2023/04/about-3-2.jpg', 'Tata BarberShop grooming tools'
where not exists (select 1 from tata_baber_about_images where id = 'about-image-2');

notify pgrst, 'reload schema';
