drop table if exists tata_baber_hero_settings;
drop table if exists tata_baber_about_images;

create table if not exists tata_baber_hero_slides (
    id text primary key,
    sort_order integer not null default 1,
    active boolean not null default true,
    image_url text not null,
    thumb_url text,
    updated_at timestamptz not null default now()
);

create index if not exists tata_baber_hero_slides_sort_order_idx on tata_baber_hero_slides (sort_order);

alter table tata_baber_hero_slides drop column if exists tab_title;
alter table tata_baber_hero_slides drop column if exists eyebrow;
alter table tata_baber_hero_slides drop column if exists address_html;
alter table tata_baber_hero_slides drop column if exists email;
alter table tata_baber_hero_slides drop column if exists phone;

create table if not exists tata_baber_admin_auth (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password text not null,
    created_at timestamptz not null default now()
);

alter table tata_baber_admin_auth disable row level security;
alter table tata_baber_hero_slides disable row level security;

insert into tata_baber_admin_auth (username, password)
select 'admin', 'admin123'
where not exists (select 1 from tata_baber_admin_auth where username = 'admin');

insert into tata_baber_admin_auth (username, password)
select 'kenbaber', 'kenbabershop1234'
where not exists (select 1 from tata_baber_admin_auth where username = 'kenbaber');

insert into storage.buckets (id, name, public)
values ('tata-baber', 'tata-baber', true)
on conflict (id) do update set public = excluded.public;

insert into tata_baber_hero_slides (id, sort_order, active, image_url, thumb_url)
select 'hero-slide-1', 1, true, './images-tatabarber/banner01.jpg', './images-tatabarber/banner01.jpg'
where not exists (select 1 from tata_baber_hero_slides where id = 'hero-slide-1');

insert into tata_baber_hero_slides (id, sort_order, active, image_url, thumb_url)
select 'hero-slide-2', 2, true, './images-tatabarber/banner01.jpg', './images-tatabarber/banner01.jpg'
where not exists (select 1 from tata_baber_hero_slides where id = 'hero-slide-2');

insert into tata_baber_hero_slides (id, sort_order, active, image_url, thumb_url)
select 'hero-slide-3', 3, true, './images-tatabarber/banner02.jpg', './images-tatabarber/banner02.jpg'
where not exists (select 1 from tata_baber_hero_slides where id = 'hero-slide-3');

notify pgrst, 'reload schema';
select pg_notify('pgrst', 'reload schema');
